"""Chart theme and builders (validated palette, one chart form per data job)."""

from .charts import (
    acwr_chart,
    activity_mix,
    attention_scores,
    decoupling_chart,
    discipline_split_chart,
    efficiency_trend,
    exercise_progression,
    fitness_fatigue,
    intensity_split,
    muscle_score_history_chart,
    muscle_volume_vs_target,
    muscle_week_heatmap,
    niggle_timeline,
    pace_by_distance,
    readiness_chart,
    recovery_trend,
    snapshot_metric_chart,
    weekly_running_volume,
    zone_distribution_chart,
)
from .theme import DARK, LIGHT, SEVERITY_ICON, Palette, palette_for, severity_color

__all__ = [
    "DARK",
    "LIGHT",
    "Palette",
    "SEVERITY_ICON",
    "acwr_chart",
    "activity_mix",
    "attention_scores",
    "decoupling_chart",
    "discipline_split_chart",
    "efficiency_trend",
    "exercise_progression",
    "fitness_fatigue",
    "intensity_split",
    "muscle_score_history_chart",
    "muscle_volume_vs_target",
    "muscle_week_heatmap",
    "niggle_timeline",
    "pace_by_distance",
    "palette_for",
    "readiness_chart",
    "recovery_trend",
    "severity_color",
    "snapshot_metric_chart",
    "weekly_running_volume",
    "zone_distribution_chart",
]
